export const browserCoreExamples = [
  "donna browser status",
  "donna browser start",
  "donna browser stop",
  "donna browser tabs",
  "donna browser open https://example.com",
  "donna browser focus abcd1234",
  "donna browser close abcd1234",
  "donna browser screenshot",
  "donna browser screenshot --full-page",
  "donna browser screenshot --ref 12",
  "donna browser snapshot",
  "donna browser snapshot --format aria --limit 200",
  "donna browser snapshot --efficient",
  "donna browser snapshot --labels",
];

export const browserActionExamples = [
  "donna browser navigate https://example.com",
  "donna browser resize 1280 720",
  "donna browser click 12 --double",
  'donna browser type 23 "hello" --submit',
  "donna browser press Enter",
  "donna browser hover 44",
  "donna browser drag 10 11",
  "donna browser select 9 OptionA OptionB",
  "donna browser upload /tmp/donna/uploads/file.pdf",
  'donna browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "donna browser dialog --accept",
  'donna browser wait --text "Done"',
  "donna browser evaluate --fn '(el) => el.textContent' --ref 7",
  "donna browser console --level error",
  "donna browser pdf",
];
