#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${DONNA_INSTALL_E2E_IMAGE:-${DONNA_INSTALL_E2E_IMAGE:-donna-install-e2e:local}}"
INSTALL_URL="${DONNA_INSTALL_URL:-${DONNA_INSTALL_URL:-https://donna.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
DONNA_E2E_MODELS="${DONNA_E2E_MODELS:-${DONNA_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e DONNA_INSTALL_URL="$INSTALL_URL" \
  -e DONNA_INSTALL_TAG="${DONNA_INSTALL_TAG:-${DONNA_INSTALL_TAG:-latest}}" \
  -e DONNA_E2E_MODELS="$DONNA_E2E_MODELS" \
  -e DONNA_INSTALL_E2E_PREVIOUS="${DONNA_INSTALL_E2E_PREVIOUS:-${DONNA_INSTALL_E2E_PREVIOUS:-}}" \
  -e DONNA_INSTALL_E2E_SKIP_PREVIOUS="${DONNA_INSTALL_E2E_SKIP_PREVIOUS:-${DONNA_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
